=== api-evangelist/amazon-license-manager/json-schema/amazon-license-manager-license-configuration-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-license-manager/refs/heads/main/json-schema/amazon-license-manager-license-configuration-schema.json",
  "title": "LicenseConfiguration",
  "description": "An AWS License Manager license configuration.",
  "type": "object",
  "properties": {
    "LicenseConfigurationId": {
      "type": "string",
      "description": "Unique ID of the license configuration.",
      "example": "lic-0e6b56b16c0c11111"
    },
    "LicenseConfigurationArn": {
      "type": "string",
      "description": "Amazon Resource Name (ARN) of the license configuration."
    },
    "Name": {
      "type": "string",
      "description": "Name of the license configuration.",
      "example": "windows-server-2022"
    },
    "LicenseCountingType": {
      "type": "string",
      "description": "Dimension for which the licenses are counted.",
      "example": "vCPU",
      "enum": [
        "vCPU",
        "Instance",
        "Core",
        "Socket"
      ]
    },
    "LicenseCount": {
      "type": "integer",
      "description": "Number of licenses managed by the license configuration.",
      "example": 100
    },
    "LicenseCountHardLimit": {
      "type": "boolean",
      "description": "Number of available licenses as a hard limit.",
      "example": true
    },
    "ConsumedLicenses": {
      "type": "integer",
      "description": "Number of licenses consumed by the license configuration.",
      "example": 45
    },
    "Status": {
      "type": "string",
      "description": "Status of the license configuration.",
      "example": "AVAILABLE"
    }
  }
}

=== api-evangelist/amazon-license-manager/examples/amazon-license-manager-license-configuration-example.json
{
  "LicenseConfigurationId": "lic-0e6b56b16c0c11111",
  "LicenseConfigurationArn": "arn:aws:service:us-east-1:123456789012:resource/example",
  "Name": "windows-server-2022",
  "LicenseCountingType": "vCPU",
  "LicenseCount": 100,
  "LicenseCountHardLimit": true,
  "ConsumedLicenses": 45,
  "Status": "AVAILABLE"
}
